/*

Copyright (c) 2004-2009 Krzysztof Ostrowski. All rights reserved.

Redistribution and use in source and binary forms,
with or without modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials provided
   with the distribution.

THIS SOFTWARE IS PROVIDED "AS IS" BY THE ABOVE COPYRIGHT HOLDER(S)
AND ALL OTHER CONTRIBUTORS AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDER(S) OR ANY OTHER
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.

*/

using System;
using System.Collections.Generic;
using System.Text;

namespace QS._qss_p_.Structure_
{
    public sealed class Library_ : QS.Fx.Inspection.Inspectable, ILibrary_
    {
        #region Constructor

        public Library_(string _identifier, IMetadata_ _metadata, IEnumerable<IDeclaration_> _declarations)
        {
            this._identifier = _identifier;
            this._metadata = _metadata;
            this._declarations = (new List<IDeclaration_>(_declarations)).ToArray();
        }

        #endregion

        #region Fields

        [QS.Fx.Base.Inspectable]
        private string _identifier;
        [QS.Fx.Base.Inspectable]
        private IMetadata_ _metadata;
        [QS.Fx.Base.Inspectable]
        private IDeclaration_[] _declarations;

        #endregion

        #region ILibrary_ Members

        IMetadata_ ILibrary_._Metadata
        {
            get { return this._metadata; }
        }

        IDeclaration_[] ILibrary_._Declarations
        {
            get { return this._declarations; }
        }

        #endregion

        #region IElement_ Members

        void IElement_._Print(QS._qss_p_.Printing_.IPrinter_ _printer)
        {
            switch (_printer._Type)
            {
                case QS._qss_p_.Printing_.Printer_.Type_._Source:
                    {
                        _printer._Print("library ");
                        this._metadata._Print(_printer);
                        _printer._Print("\n{\n");
                        _printer._Shift(1);
                    }
                    break;

                case QS._qss_p_.Printing_.Printer_.Type_._Compiled:
                    {
                        _printer._Print("// This file has been generated by the Live Distributed Objects compiler at " + DateTime.Now.ToString() + ".\n");
                        _printer._Print("// The creators of the compiler assume no responsibility for any loss or damage resulting from the use of this software.\n");
                        _printer._Print("\n");
                        _printer._Print("#region dependencies and metadata\n");
                        _printer._Print("\n");
                        _printer._Print("using System;\n");
                        _printer._Print("using System.Collections.Generic;\n");
                        //_printer._Print("using System.Reflection;\n");
                        //_printer._Print("using System.Runtime.CompilerServices;\n");
                        //_printer._Print("using System.Runtime.InteropServices;\n");
                        _printer._Print("using System.Text;\n");
                        _printer._Print("\n");
                        //_printer._Print("[assembly: AssemblyTitle(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyDescription(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyConfiguration(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyCompany(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyProduct(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyCopyright(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyTrademark(\"\")]\n");
                        //_printer._Print("[assembly: AssemblyCulture(\"\")]\n");
                        //_printer._Print("[assembly: ComVisible(false)]\n");
                        //_printer._Print("[assembly: Guid(\"" + Guid.NewGuid() + "\")]\n");
                        //_printer._Print("[assembly: AssemblyVersion(\"1.0.0.0\")]\n");
                        //_printer._Print("[assembly: AssemblyFileVersion(\"1.0.0.0\")]\n");
                        _printer._Print("[assembly: QS.Fx.Reflection.Library(");
                        this._metadata._Print(_printer);
                        _printer._Print(")]\n");
                        _printer._Print("\n");
                        _printer._Print("#endregion\n");
                        _printer._Print("\n");
                        _printer._Print("namespace liveobjects_library_" + this._metadata._Identifier + "\n{\n");
                        _printer._Shift(1);
                    }
                    break;

                default:
                    throw new NotImplementedException();
            }

            bool _isfirst = true;
            foreach (IDeclaration_ _declaration in this._declarations)
            {
                if (_isfirst)
                    _isfirst = false;
                else
                    _printer._Print("\n");
                _declaration._Declare(_printer);
            }

            switch (_printer._Type)
            {
                case QS._qss_p_.Printing_.Printer_.Type_._Source:
                    {
                        _printer._Shift(-1);
                        _printer._Print("}\n");
                    }
                    break;

                case QS._qss_p_.Printing_.Printer_.Type_._Compiled:
                    {
                        _printer._Shift(-1);
                        _printer._Print("}\n");
                    }
                    break;

                default:
                    throw new NotImplementedException();
            }
        }

        #endregion
    }
}
