// This code was generated by the Managed Package Parser Generator


using System;
using System.Collections.Generic;
using System.Text;
using Babel.ParserGenerator;
using QS._qss_p_.ParserGenerator_;

namespace QS._qss_p_.Parser_
{
public enum Tokens {error=127,EOF=128,
    IDENTIFIER=129,NUMBER=130,STRING=131,UUID=132,KWBOOL=133,KWCLASS=134,KWCONJUNCTION=135,KWCONST=136,
    KWDISJUNCTION=137,KWDOWN=138,KWELSEWHERE=139,KWEMPTY=140,KWENDPOINT=141,KWFALSE=142,KWFRESH=143,KWID=144,
    KWINCOMPLETE=145,KWINDEPENDENTLY=146,KWINT=147,KWINTERFACE=148,KWINTERSECTION=149,KWLIBRARY=150,KWMAX=151,KWMESSAGE=152,
    KWMIN=153,KWOBJECT=154,KWOPERATOR=155,KWOTHER=156,KWPRODUCT=157,KWSAME=158,KWSINGLETON=159,KWSOME=160,
    KWSTRONG=161,KWSUM=162,KWTRUE=163,KWUNCOORDINATED=164,KWUNION=165,KWUNORDERED=166,KWUP=167,KWUUID=168,
    KWVERSION=169,KWVALUE=170,KWWEAK=171,KWWHERE=172,EQ=173,NEQ=174,GT=175,GTE=176,
    LT=177,LTE=178,AMPAMP=179,BARBAR=180,ASSIGN=181,DOTDOT=182,maxParseToken=183,LEX_WHITE=184,
    LEX_COMMENT=185,LEX_ERROR=186,UMINUS=187,LOWER_THAN_ELSEWHERE=188};

public partial struct LexValue
#line 38 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
    public QS._qss_p_.Structure_.IAssignment_ _assignment;
    public QS._qss_p_.Structure_.ICode_ _code;    
    public QS._qss_p_.Structure_.IDeclaration_ _declaration;
    public List<QS._qss_p_.Structure_.IDeclaration_> _declarations;
    public QS._qss_p_.Structure_.IDependency_ _dependency;
    public QS._qss_p_.Structure_.IEmbedded_ _embedded;
    public List<QS._qss_p_.Structure_.IEmbedded_> _embeddeds;
    public QS._qss_p_.Structure_.IEmbedding_ _embedding;
    public QS._qss_p_.Structure_.IEmbeddedFlow_ _embeddedflow;
    public QS._qss_p_.Structure_.IEndpoint_ _endpoint;
    public QS._qss_p_.Structure_.IEndpointClass_ _endpointclass;
    public List<QS._qss_p_.Structure_.IEndpoint_> _endpoints;
    public QS._qss_p_.Structure_.IExpression_ _expression;
    public QS._qss_p_.Structure_.IFlow_ _flow;
    public QS._qss_p_.Structure_.IFlowClass_ _flowclass;
    public List<QS._qss_p_.Structure_.IFlow_> _flows;
	public string _identifier;
    public List<string> _identifiers;
    public QS._qss_p_.Structure_.IInterfaceClass_ _interfaceclass;
    public QS._qss_p_.Structure_.ILibrary_ _library;
    public QS._qss_p_.Structure_.IMetadata_ _metadata;
    public int _number;
    public QS._qss_p_.Structure_.IObject_ _object;
    public QS._qss_p_.Structure_.IObjectClass_ _objectclass;
    public QS._qss_p_.Structure_.IOperation_ _operation;
    public QS._qss_p_.Structure_.IOperator_ _operator;
    public QS._qss_p_.Structure_.IOperatorClass_ _operatorclass;
    public QS._qss_p_.Structure_.Operator_.Type_ _operatortype;
    public QS._qss_p_.Structure_.IParameter_ _parameter;
    public List<QS._qss_p_.Structure_.IParameter_> _parameters;    
    public QS._qss_p_.Structure_.Properties_ _properties;
    public QS._qss_p_.Structure_.IStatement_ _statement;
    public List<QS._qss_p_.Structure_.IStatement_> _statements;
	public string _string;
	public string _uuid;
	public QS._qss_p_.Structure_.IValue_ _value;
    public List<QS._qss_p_.Structure_.IValue_> _values;
    public QS._qss_p_.Structure_.IValueClass_ _valueclass;
    public List<QS._qss_p_.Structure_.IValueClass_> _valueclasses;
}
// Abstract base class for MPLEX scanners
public abstract class ScanBase : AScanner<LexValue,LexLocation> {
    protected abstract int CurrentSc { get; set; }
    //
    // Override the virtual EolState property if the scanner state is more
    // complicated then a simple copy of the current start state ordinal
    //
    public virtual int EolState { get { return CurrentSc; } set { CurrentSc = value; } }
}

public partial class Parser: ShiftReduceParser<LexValue, LexLocation>
{
#line 80 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"

    ErrorHandler handler = null;
    public void SetHandler(ErrorHandler hdlr) { handler = hdlr; }
    internal void CallHdlr(string msg, LexLocation val)
    {
        handler.AddError(msg, val.sLin, val.sCol, val.eCol - val.sCol);
    }

	internal QS._qss_p_.Structure_.IEnvironment_ _environment = new QS._qss_p_.Structure_.Environment_(null);
	internal List<QS._qss_p_.Structure_.IUnresolved_> _unresolved = new List<QS._qss_p_.Structure_.IUnresolved_>();
	internal Stack<QS._qss_p_.Structure_.IMetadata_> _metadata_stack = new Stack<QS._qss_p_.Structure_.IMetadata_>();
	internal Stack<IEnumerable<QS._qss_p_.Structure_.IParameter_>> _parameters_stack = new Stack<IEnumerable<QS._qss_p_.Structure_.IParameter_>>();
	internal List<QS._qss_p_.Structure_.IDeclaration_> _automatic_declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
	internal QS._qss_p_.Structure_.ILibrary_ _library;
	internal QS._qss_p_.Structure_.ILibrary_ _Library
	{
		get { return this._library; }
	}	    
	
	void _GenerateClassParametersAndDeclarations(IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters,
		out IEnumerable<QS._qss_p_.Structure_.IParameter_> _class_parameters, out IEnumerable<QS._qss_p_.Structure_.IDeclaration_> _class_declarations)
	{		
		if (_parameters != null)
		{
			List<QS._qss_p_.Structure_.IParameter_> _list_of_class_parameters = new List<QS._qss_p_.Structure_.IParameter_>();
			List<QS._qss_p_.Structure_.IDeclaration_> _list_of_class_declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
			foreach (QS._qss_p_.Structure_.IParameter_ _parameter in _parameters)
			{
				if (((QS._qss_p_.Structure_.IDeclaration_) _parameter)._Type != QS._qss_p_.Structure_.Declaration_.Type_._Value)
				{
					_list_of_class_parameters.Add(_parameter);
					_list_of_class_declarations.Add(new QS._qss_p_.Structure_.Declaration_Reference_(_parameter, null));
				}
			}
			_class_parameters = _list_of_class_parameters;
			_class_declarations = _list_of_class_declarations;
		}
		else
		{
			_class_parameters = null;
			_class_declarations = null;
		}
	}			
/*	
	QS._qss_p_.Structure_.Flow_.Type_ _flowtype = QS._qss_p_.Structure_.Flow_.Type_._Embedded;
*/	
  protected override void Initialize()
  {
    this.errToken = (int)Tokens.error;
    this.eofToken = (int)Tokens.EOF;

    states=new State[181];
    AddState(0,new State(new int[]{150,3},new int[]{-13,1}));
    AddState(1,new State(new int[]{128,2}));
    AddState(2,new State(-1));
    AddState(3,new State(new int[]{129,27,131,28,132,73},new int[]{-14,4,-15,72}));
    AddState(4,new State(new int[]{123,5}));
    AddState(5,new State(new int[]{170,12,155,103,148,147,141,155,154,163},new int[]{-6,6,-7,8,-3,10,-48,11,-21,102,-12,146,-10,154,-18,162,-35,178,-19,179,-16,180}));
    AddState(6,new State(new int[]{125,7}));
    AddState(7,new State(-22));
    AddState(8,new State(new int[]{170,12,155,103,148,147,141,155,154,163,125,-14},new int[]{-6,9,-7,8,-3,10,-48,11,-21,102,-12,146,-10,154,-18,162,-35,178,-19,179,-16,180}));
    AddState(9,new State(-13));
    AddState(10,new State(-15));
    AddState(11,new State(-5));
    AddState(12,new State(new int[]{134,13,129,27,131,28,132,73},new int[]{-14,82,-15,72}));
    AddState(13,new State(new int[]{129,27,131,28,132,73},new int[]{-14,14,-15,72}));
    AddState(14,new State(-99,new int[]{-66,15}));
    AddState(15,new State(new int[]{177,55,123,-59},new int[]{-29,16}));
    AddState(16,new State(-100,new int[]{-67,17}));
    AddState(17,new State(new int[]{123,19},new int[]{-49,18}));
    AddState(18,new State(-101));
    AddState(19,new State(new int[]{133,31,147,32,40,33,123,39,129,43,125,-88},new int[]{-41,20,-32,22,-47,25,-51,30,-50,42}));
    AddState(20,new State(new int[]{125,21}));
    AddState(21,new State(-102));
    AddState(22,new State(new int[]{59,23}));
    AddState(23,new State(new int[]{133,31,147,32,40,33,123,39,129,43,125,-88},new int[]{-41,24,-32,22,-47,25,-51,30,-50,42}));
    AddState(24,new State(-87));
    AddState(25,new State(new int[]{129,27,131,28},new int[]{-15,26}));
    AddState(26,new State(-71));
    AddState(27,new State(-28));
    AddState(28,new State(new int[]{129,29}));
    AddState(29,new State(-29));
    AddState(30,new State(-95));
    AddState(31,new State(-104));
    AddState(32,new State(-105));
    AddState(33,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-52,34,-47,36,-51,30,-50,42}));
    AddState(34,new State(new int[]{41,35}));
    AddState(35,new State(-106));
    AddState(36,new State(new int[]{44,37,41,-98}));
    AddState(37,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-52,38,-47,36,-51,30,-50,42}));
    AddState(38,new State(-97));
    AddState(39,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-47,40,-51,30,-50,42}));
    AddState(40,new State(new int[]{125,41}));
    AddState(41,new State(-107));
    AddState(42,new State(-96));
    AddState(43,new State(new int[]{177,45,129,-65,131,-65,44,-65,41,-65,125,-65},new int[]{-9,44}));
    AddState(44,new State(-103));
    AddState(45,new State(new int[]{133,31,147,32,40,33,123,39,129,53},new int[]{-8,46,-5,48,-51,51,-4,52}));
    AddState(46,new State(new int[]{175,47}));
    AddState(47,new State(-64));
    AddState(48,new State(new int[]{44,49,175,-63}));
    AddState(49,new State(new int[]{133,31,147,32,40,33,123,39,129,53},new int[]{-8,50,-5,48,-51,51,-4,52}));
    AddState(50,new State(-62));
    AddState(51,new State(-60));
    AddState(52,new State(-61));
    AddState(53,new State(new int[]{177,45,44,-65,175,-65,126,-65,129,-65},new int[]{-9,54}));
    AddState(54,new State(-16));
    AddState(55,new State(new int[]{170,61,133,31,147,32,40,33,123,39,129,53},new int[]{-28,56,-25,58,-51,66,-4,69}));
    AddState(56,new State(new int[]{175,57}));
    AddState(57,new State(-58));
    AddState(58,new State(new int[]{44,59,175,-57}));
    AddState(59,new State(new int[]{170,61,133,31,147,32,40,33,123,39,129,53},new int[]{-28,60,-25,58,-51,66,-4,69}));
    AddState(60,new State(-56));
    AddState(61,new State(new int[]{134,62,126,64}));
    AddState(62,new State(new int[]{129,63}));
    AddState(63,new State(-46));
    AddState(64,new State(new int[]{129,65}));
    AddState(65,new State(-47));
    AddState(66,new State(new int[]{126,67}));
    AddState(67,new State(new int[]{129,68}));
    AddState(68,new State(-48));
    AddState(69,new State(new int[]{126,70}));
    AddState(70,new State(new int[]{129,71}));
    AddState(71,new State(-49));
    AddState(72,new State(-23));
    AddState(73,new State(new int[]{129,74,131,75,96,77}));
    AddState(74,new State(-24));
    AddState(75,new State(new int[]{129,76}));
    AddState(76,new State(-25));
    AddState(77,new State(new int[]{130,78}));
    AddState(78,new State(new int[]{129,79,131,80}));
    AddState(79,new State(-26));
    AddState(80,new State(new int[]{129,81}));
    AddState(81,new State(-27));
    AddState(82,new State(-66,new int[]{-64,83}));
    AddState(83,new State(new int[]{177,90,123,-55},new int[]{-27,84}));
    AddState(84,new State(-67,new int[]{-65,85}));
    AddState(85,new State(new int[]{123,87},new int[]{-36,86}));
    AddState(86,new State(-68));
    AddState(87,new State(new int[]{133,31,147,32,40,33,123,39,129,43,125,-88},new int[]{-41,88,-32,22,-47,25,-51,30,-50,42}));
    AddState(88,new State(new int[]{125,89}));
    AddState(89,new State(-69));
    AddState(90,new State(new int[]{133,31,147,32,40,33,123,39,129,53,170,61},new int[]{-26,91,-23,93,-24,96,-51,97,-4,99,-25,101}));
    AddState(91,new State(new int[]{175,92}));
    AddState(92,new State(-54));
    AddState(93,new State(new int[]{44,94,175,-53}));
    AddState(94,new State(new int[]{133,31,147,32,40,33,123,39,129,53,170,61},new int[]{-26,95,-23,93,-24,96,-51,97,-4,99,-25,101}));
    AddState(95,new State(-52));
    AddState(96,new State(-44));
    AddState(97,new State(new int[]{129,98,126,67}));
    AddState(98,new State(-50));
    AddState(99,new State(new int[]{129,100,126,70}));
    AddState(100,new State(-51));
    AddState(101,new State(-45));
    AddState(102,new State(-6));
    AddState(103,new State(new int[]{134,104,129,27,131,28,132,73},new int[]{-14,128,-15,72}));
    AddState(104,new State(new int[]{129,27,131,28,132,73},new int[]{-14,105,-15,72}));
    AddState(105,new State(-40,new int[]{-62,106}));
    AddState(106,new State(new int[]{177,55,40,-59},new int[]{-29,107}));
    AddState(107,new State(-41,new int[]{-63,108}));
    AddState(108,new State(new int[]{40,110},new int[]{-22,109}));
    AddState(109,new State(-42));
    AddState(110,new State(new int[]{133,31,147,32,40,33,123,39,129,43,41,-76},new int[]{-37,111,-38,122,-30,123,-47,126,-51,30,-50,42}));
    AddState(111,new State(new int[]{41,112}));
    AddState(112,new State(new int[]{58,115,59,-84},new int[]{-44,113}));
    AddState(113,new State(new int[]{59,114}));
    AddState(114,new State(-43));
    AddState(115,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-45,116,-33,117,-47,120,-51,30,-50,42}));
    AddState(116,new State(-83));
    AddState(117,new State(new int[]{44,118,59,-86,123,-86}));
    AddState(118,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-45,119,-33,117,-47,120,-51,30,-50,42}));
    AddState(119,new State(-85));
    AddState(120,new State(new int[]{129,27,131,28},new int[]{-15,121}));
    AddState(121,new State(-73));
    AddState(122,new State(-75));
    AddState(123,new State(new int[]{44,124,41,-78}));
    AddState(124,new State(new int[]{133,31,147,32,40,33,123,39,129,43},new int[]{-38,125,-30,123,-47,126,-51,30,-50,42}));
    AddState(125,new State(-77));
    AddState(126,new State(new int[]{129,27,131,28},new int[]{-15,127}));
    AddState(127,new State(-70));
    AddState(128,new State(-36,new int[]{-60,129}));
    AddState(129,new State(new int[]{177,90,40,-55},new int[]{-27,130}));
    AddState(130,new State(-37,new int[]{-61,131}));
    AddState(131,new State(new int[]{40,133},new int[]{-20,132}));
    AddState(132,new State(-38));
    AddState(133,new State(new int[]{133,31,147,32,40,33,123,39,129,43,41,-76},new int[]{-37,134,-38,122,-30,123,-47,126,-51,30,-50,42}));
    AddState(134,new State(new int[]{41,135}));
    AddState(135,new State(new int[]{58,115,123,-84},new int[]{-44,136}));
    AddState(136,new State(new int[]{123,137}));
    AddState(137,new State(new int[]{133,31,147,32,40,33,123,39,129,43,125,-80},new int[]{-39,138,-40,140,-31,141,-47,144,-51,30,-50,42}));
    AddState(138,new State(new int[]{125,139}));
    AddState(139,new State(-39));
    AddState(140,new State(-79));
    AddState(141,new State(new int[]{59,142}));
    AddState(142,new State(new int[]{133,31,147,32,40,33,123,39,129,43,125,-82},new int[]{-40,143,-31,141,-47,144,-51,30,-50,42}));
    AddState(143,new State(-81));
    AddState(144,new State(new int[]{129,27,131,28},new int[]{-15,145}));
    AddState(145,new State(-72));
    AddState(146,new State(-7));
    AddState(147,new State(new int[]{134,148}));
    AddState(148,new State(new int[]{129,27,131,28,132,73},new int[]{-14,149,-15,72}));
    AddState(149,new State(-20,new int[]{-56,150}));
    AddState(150,new State(new int[]{177,55,123,-59},new int[]{-29,151}));
    AddState(151,new State(new int[]{123,152}));
    AddState(152,new State(new int[]{125,153}));
    AddState(153,new State(-21));
    AddState(154,new State(-8));
    AddState(155,new State(new int[]{134,156}));
    AddState(156,new State(new int[]{129,27,131,28,132,73},new int[]{-14,157,-15,72}));
    AddState(157,new State(-18,new int[]{-55,158}));
    AddState(158,new State(new int[]{177,55,123,-59},new int[]{-29,159}));
    AddState(159,new State(new int[]{123,160}));
    AddState(160,new State(new int[]{125,161}));
    AddState(161,new State(-19));
    AddState(162,new State(-9));
    AddState(163,new State(new int[]{134,164,129,27,131,28,132,73},new int[]{-14,170,-15,72}));
    AddState(164,new State(new int[]{129,27,131,28,132,73},new int[]{-14,165,-15,72}));
    AddState(165,new State(-34,new int[]{-59,166}));
    AddState(166,new State(new int[]{177,55,123,-59},new int[]{-29,167}));
    AddState(167,new State(new int[]{123,168}));
    AddState(168,new State(new int[]{125,169}));
    AddState(169,new State(-35));
    AddState(170,new State(-30,new int[]{-57,171}));
    AddState(171,new State(new int[]{177,90,123,-55},new int[]{-27,172}));
    AddState(172,new State(-31,new int[]{-58,173}));
    AddState(173,new State(-17,new int[]{-17,174,-11,175}));
    AddState(174,new State(-32));
    AddState(175,new State(new int[]{123,176}));
    AddState(176,new State(new int[]{125,177}));
    AddState(177,new State(-33));
    AddState(178,new State(-10));
    AddState(179,new State(-11));
    AddState(180,new State(-12));

    rules=new Rule[108];
    rules[1]=new Rule(-53, new int[]{-13,128});
    rules[2]=new Rule(-54, new int[]{});
    rules[3]=new Rule(-1, new int[]{-46,61,-54,-2});
    rules[4]=new Rule(-2, new int[]{});
    rules[5]=new Rule(-3, new int[]{-48});
    rules[6]=new Rule(-3, new int[]{-21});
    rules[7]=new Rule(-3, new int[]{-12});
    rules[8]=new Rule(-3, new int[]{-10});
    rules[9]=new Rule(-3, new int[]{-18});
    rules[10]=new Rule(-3, new int[]{-35});
    rules[11]=new Rule(-3, new int[]{-19});
    rules[12]=new Rule(-3, new int[]{-16});
    rules[13]=new Rule(-6, new int[]{-7,-6});
    rules[14]=new Rule(-6, new int[]{-7});
    rules[15]=new Rule(-7, new int[]{-3});
    rules[16]=new Rule(-4, new int[]{129,-9});
    rules[17]=new Rule(-11, new int[]{});
    rules[18]=new Rule(-55, new int[]{});
    rules[19]=new Rule(-10, new int[]{141,134,-14,-55,-29,123,125});
    rules[20]=new Rule(-56, new int[]{});
    rules[21]=new Rule(-12, new int[]{148,134,-14,-56,-29,123,125});
    rules[22]=new Rule(-13, new int[]{150,-14,123,-6,125});
    rules[23]=new Rule(-14, new int[]{-15});
    rules[24]=new Rule(-14, new int[]{132,129});
    rules[25]=new Rule(-14, new int[]{132,131,129});
    rules[26]=new Rule(-14, new int[]{132,96,130,129});
    rules[27]=new Rule(-14, new int[]{132,96,130,131,129});
    rules[28]=new Rule(-15, new int[]{129});
    rules[29]=new Rule(-15, new int[]{131,129});
    rules[30]=new Rule(-57, new int[]{});
    rules[31]=new Rule(-58, new int[]{});
    rules[32]=new Rule(-16, new int[]{154,-14,-57,-27,-58,-17});
    rules[33]=new Rule(-17, new int[]{-11,123,125});
    rules[34]=new Rule(-59, new int[]{});
    rules[35]=new Rule(-18, new int[]{154,134,-14,-59,-29,123,125});
    rules[36]=new Rule(-60, new int[]{});
    rules[37]=new Rule(-61, new int[]{});
    rules[38]=new Rule(-19, new int[]{155,-14,-60,-27,-61,-20});
    rules[39]=new Rule(-20, new int[]{40,-37,41,-44,123,-39,125});
    rules[40]=new Rule(-62, new int[]{});
    rules[41]=new Rule(-63, new int[]{});
    rules[42]=new Rule(-21, new int[]{155,134,-14,-62,-29,-63,-22});
    rules[43]=new Rule(-22, new int[]{40,-37,41,-44,59});
    rules[44]=new Rule(-23, new int[]{-24});
    rules[45]=new Rule(-23, new int[]{-25});
    rules[46]=new Rule(-25, new int[]{170,134,129});
    rules[47]=new Rule(-25, new int[]{170,126,129});
    rules[48]=new Rule(-25, new int[]{-51,126,129});
    rules[49]=new Rule(-25, new int[]{-4,126,129});
    rules[50]=new Rule(-24, new int[]{-51,129});
    rules[51]=new Rule(-24, new int[]{-4,129});
    rules[52]=new Rule(-26, new int[]{-23,44,-26});
    rules[53]=new Rule(-26, new int[]{-23});
    rules[54]=new Rule(-27, new int[]{177,-26,175});
    rules[55]=new Rule(-27, new int[]{});
    rules[56]=new Rule(-28, new int[]{-25,44,-28});
    rules[57]=new Rule(-28, new int[]{-25});
    rules[58]=new Rule(-29, new int[]{177,-28,175});
    rules[59]=new Rule(-29, new int[]{});
    rules[60]=new Rule(-5, new int[]{-51});
    rules[61]=new Rule(-5, new int[]{-4});
    rules[62]=new Rule(-8, new int[]{-5,44,-8});
    rules[63]=new Rule(-8, new int[]{-5});
    rules[64]=new Rule(-9, new int[]{177,-8,175});
    rules[65]=new Rule(-9, new int[]{});
    rules[66]=new Rule(-64, new int[]{});
    rules[67]=new Rule(-65, new int[]{});
    rules[68]=new Rule(-35, new int[]{170,-14,-64,-27,-65,-36});
    rules[69]=new Rule(-36, new int[]{123,-41,125});
    rules[70]=new Rule(-30, new int[]{-47,-15});
    rules[71]=new Rule(-32, new int[]{-47,-15});
    rules[72]=new Rule(-31, new int[]{-47,-15});
    rules[73]=new Rule(-33, new int[]{-47,-15});
    rules[74]=new Rule(-34, new int[]{129});
    rules[75]=new Rule(-37, new int[]{-38});
    rules[76]=new Rule(-37, new int[]{});
    rules[77]=new Rule(-38, new int[]{-30,44,-38});
    rules[78]=new Rule(-38, new int[]{-30});
    rules[79]=new Rule(-39, new int[]{-40});
    rules[80]=new Rule(-39, new int[]{});
    rules[81]=new Rule(-40, new int[]{-31,59,-40});
    rules[82]=new Rule(-40, new int[]{-31,59});
    rules[83]=new Rule(-44, new int[]{58,-45});
    rules[84]=new Rule(-44, new int[]{});
    rules[85]=new Rule(-45, new int[]{-33,44,-45});
    rules[86]=new Rule(-45, new int[]{-33});
    rules[87]=new Rule(-41, new int[]{-32,59,-41});
    rules[88]=new Rule(-41, new int[]{});
    rules[89]=new Rule(-42, new int[]{-43});
    rules[90]=new Rule(-42, new int[]{});
    rules[91]=new Rule(-43, new int[]{-32,44,-43});
    rules[92]=new Rule(-43, new int[]{-32});
    rules[93]=new Rule(-46, new int[]{-34,44,-46});
    rules[94]=new Rule(-46, new int[]{-34});
    rules[95]=new Rule(-47, new int[]{-51});
    rules[96]=new Rule(-47, new int[]{-50});
    rules[97]=new Rule(-52, new int[]{-47,44,-52});
    rules[98]=new Rule(-52, new int[]{-47});
    rules[99]=new Rule(-66, new int[]{});
    rules[100]=new Rule(-67, new int[]{});
    rules[101]=new Rule(-48, new int[]{170,134,-14,-66,-29,-67,-49});
    rules[102]=new Rule(-49, new int[]{123,-41,125});
    rules[103]=new Rule(-50, new int[]{129,-9});
    rules[104]=new Rule(-51, new int[]{133});
    rules[105]=new Rule(-51, new int[]{147});
    rules[106]=new Rule(-51, new int[]{40,-52,41});
    rules[107]=new Rule(-51, new int[]{123,-47,125});

    nonTerminals = new string[] {"", "Assignment", "Assignment_Body", "Declaration", 
      "Declaration_Reference", "Parameter_Value", "Declarations", "Declarations_Body", 
      "Parameters_Values", "Parameters_Values_Optional", "EndpointClass_Declaration", 
      "EndpointClass_Functional", "InterfaceClass_Declaration", "Library", "Metadata", 
      "Metadata_Internal", "Object_Declaration", "Object_Declaration_Body", "ObjectClass_Declaration", 
      "Operator_Declaration", "Operator_Declaration_Body", "OperatorClass_Declaration", 
      "OperatorClass_Declaration_Body", "Parameter_Declaration", "Parameter_Declaration_Value", 
      "Parameter_Declaration_Class", "Parameters_Declarations", "Parameters_Declarations_Optional", 
      "Parameters_Declarations_Classes", "Parameters_Declarations_Classes_Optional", 
      "Value_Incoming", "Value_Internal", "Value_Member", "Value_Outgoing", "Value_Reference", 
      "Value_Declaration", "Value_Declaration_Body", "Values_Incoming", "Values_Incoming_Body", 
      "Values_Internal", "Values_Internal_Body", "Values_Members", "Values_Members_Commas", 
      "Values_Members_Commas_Body", "Values_Outgoing", "Values_Outgoing_Body", 
      "Values_References", "ValueClass", "ValueClass_Declaration", "ValueClass_Declaration_Body", 
      "ValueClass_Reference", "ValueClass_Unambiguous", "ValueClasses", "$accept", 
      "@1", "@2", "@3", "@4", "@5", "@6", "@7", "@8", "@9", "@10", "@11", "@12", 
      "@13", "@14", };
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // @1 -> /* empty */
#line 262 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
		}
        break;
      case 3: // Assignment -> Values_References '=' @1 Assignment_Body 
#line 265 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._assignment = value_stack.array[value_stack.top-1]._assignment;
		}
        break;
      case 4: // Assignment_Body -> /* empty */
#line 274 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._assignment = null;
		}
        break;
      case 5: // Declaration -> ValueClass_Declaration 
#line 293 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._valueclass;
		}
        break;
      case 6: // Declaration -> OperatorClass_Declaration 
#line 297 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._operatorclass;
		}
        break;
      case 7: // Declaration -> InterfaceClass_Declaration 
#line 301 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._interfaceclass;
		}
        break;
      case 8: // Declaration -> EndpointClass_Declaration 
#line 305 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._endpointclass;
		}
        break;
      case 9: // Declaration -> ObjectClass_Declaration 
#line 309 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{		
			yyval._declaration = value_stack.array[value_stack.top-1]._objectclass;
		}
        break;
      case 10: // Declaration -> Value_Declaration 
#line 313 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._value;
		}
        break;
      case 11: // Declaration -> Operator_Declaration 
#line 317 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._operator;
		}
        break;
      case 12: // Declaration -> Object_Declaration 
#line 321 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{		
			yyval._declaration = value_stack.array[value_stack.top-1]._object;
		}
        break;
      case 13: // Declarations -> Declarations_Body Declarations 
#line 330 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = value_stack.array[value_stack.top-2]._declarations;
			yyval._declarations.AddRange(value_stack.array[value_stack.top-1]._declarations);
		}
        break;
      case 14: // Declarations -> Declarations_Body 
#line 335 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{ 
			yyval._declarations = value_stack.array[value_stack.top-1]._declarations;
		}
        break;
      case 15: // Declarations_Body -> Declaration 
#line 344 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
			foreach (QS._qss_p_.Structure_.IDeclaration_ _declaration in this._automatic_declarations)			
			{
				yyval._declarations.Add(_declaration);
				/* this._environment._Add	(_declaration); */
			}
			this._automatic_declarations.Clear();
			yyval._declarations.Add(value_stack.array[value_stack.top-1]._declaration);
			/* this._environment._Add	($1); */
		}
        break;
      case 16: // Declaration_Reference -> IDENTIFIER Parameters_Values_Optional 
#line 361 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.Declaration_Reference_ _reference = new QS._qss_p_.Structure_.Declaration_Reference_(this._environment, value_stack.array[value_stack.top-2]._identifier, value_stack.array[value_stack.top-1]._declarations);
			this._unresolved.Add(_reference);
			yyval._declaration = _reference; 
		}
        break;
      case 17: // EndpointClass_Functional -> /* empty */
#line 437 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._endpointclass = new QS._qss_p_.Structure_.EndpointClass_DualInterface_
			(
				QS._qss_p_.Structure_.InterfaceClass_Primitive_._Interface,
				QS._qss_p_.Structure_.InterfaceClass_Primitive_._Interface
			);
		}
        break;
      case 18: // @2 -> /* empty */
#line 462 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
		}
        break;
      case 19: // EndpointClass_Declaration -> KWENDPOINT KWCLASS Metadata @2 Parameters_Declarations_Classes_Optional '{' '}' 
#line 466 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			throw new NotImplementedException();
/* ....................................................................................................			
			QS._qss_p_.Structure_.EndpointClass_Custom_ _endpointclass = new QS._qss_p_.Structure_.EndpointClass_Custom_($3._Name, $3, $5);
			$$ = _endpointclass;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_endpointclass);
*/			
		}
        break;
      case 20: // @3 -> /* empty */
#line 703 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
		}
        break;
      case 21: // InterfaceClass_Declaration -> KWINTERFACE KWCLASS Metadata @3 Parameters_Declarations_Classes_Optional '{' '}' 
#line 707 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.InterfaceClass_Custom_ _interfaceclass = new QS._qss_p_.Structure_.InterfaceClass_Custom_(value_stack.array[value_stack.top-5]._metadata._Name, value_stack.array[value_stack.top-5]._metadata, value_stack.array[value_stack.top-3]._parameters);
			yyval._interfaceclass = _interfaceclass;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_interfaceclass);
		}
        break;
      case 22: // Library -> KWLIBRARY Metadata '{' Declarations '}' 
#line 747 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._library = new QS._qss_p_.Structure_.Library_(value_stack.array[value_stack.top-4]._metadata._Name, value_stack.array[value_stack.top-4]._metadata, value_stack.array[value_stack.top-2]._declarations);
			foreach (QS._qss_p_.Structure_.IUnresolved_ _unresolved in this._unresolved)
				_unresolved._Resolve();
			yyval._library = this._library;
		}
        break;
      case 23: // Metadata -> Metadata_Internal 
#line 759 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = value_stack.array[value_stack.top-1]._metadata;
		}
        break;
      case 24: // Metadata -> UUID IDENTIFIER 
#line 763 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(value_stack.array[value_stack.top-2]._uuid, "0", value_stack.array[value_stack.top-1]._identifier, null);
		}
        break;
      case 25: // Metadata -> UUID STRING IDENTIFIER 
#line 767 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(value_stack.array[value_stack.top-3]._uuid, "0", value_stack.array[value_stack.top-1]._identifier, value_stack.array[value_stack.top-2]._string);
		}
        break;
      case 26: // Metadata -> UUID '`' NUMBER IDENTIFIER 
#line 771 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(value_stack.array[value_stack.top-4]._uuid, value_stack.array[value_stack.top-2]._number.ToString(), value_stack.array[value_stack.top-1]._identifier, null);
		}
        break;
      case 27: // Metadata -> UUID '`' NUMBER STRING IDENTIFIER 
#line 775 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(value_stack.array[value_stack.top-5]._uuid, value_stack.array[value_stack.top-3]._number.ToString(), value_stack.array[value_stack.top-1]._identifier, value_stack.array[value_stack.top-2]._string);
		}
        break;
      case 28: // Metadata_Internal -> IDENTIFIER 
#line 784 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", value_stack.array[value_stack.top-1]._identifier, string.Empty);
		}
        break;
      case 29: // Metadata_Internal -> STRING IDENTIFIER 
#line 788 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._metadata = new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", value_stack.array[value_stack.top-1]._identifier, value_stack.array[value_stack.top-2]._string);
		}
        break;
      case 30: // @4 -> /* empty */
#line 797 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
			this._metadata_stack.Push(value_stack.array[value_stack.top-1]._metadata);
		}
        break;
      case 31: // @5 -> /* empty */
#line 802 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._parameters_stack.Push(value_stack.array[value_stack.top-1]._parameters);
		}
        break;
      case 32: // Object_Declaration -> KWOBJECT Metadata @4 Parameters_Declarations_Optional @5 Object_Declaration_Body 
#line 806 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IObject_ _object = value_stack.array[value_stack.top-1]._object;
			yyval._object = _object;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_object);
		}
        break;
      case 33: // Object_Declaration_Body -> EndpointClass_Functional '{' '}' 
#line 818 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IMetadata_ _metadata = this._metadata_stack.Pop();
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = this._parameters_stack.Pop(); 
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _class_parameters;
			IEnumerable<QS._qss_p_.Structure_.IDeclaration_> _class_declarations;
			_GenerateClassParametersAndDeclarations(_parameters, out _class_parameters, out _class_declarations);
			string _identifier = _metadata._Name;
			List<QS._qss_p_.Structure_.IEndpoint_> _objectclass_endpoints = new List<QS._qss_p_.Structure_.IEndpoint_>();
			_objectclass_endpoints.Add(new QS._qss_p_.Structure_.Endpoint_Member_(null, null, value_stack.array[value_stack.top-3]._endpointclass));			
			QS._qss_p_.Structure_.IObjectClass_ _objectclass = 
				new QS._qss_p_.Structure_.ObjectClass_Custom_(
					_identifier, new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", _identifier, string.Empty), _class_parameters, _objectclass_endpoints);
			this._automatic_declarations.Add(_objectclass);			
			List<QS._qss_p_.Structure_.IEndpoint_> _object_endpoints = new List<QS._qss_p_.Structure_.IEndpoint_>();
			_object_endpoints.Add(new QS._qss_p_.Structure_.Endpoint_Internal_(null, null, value_stack.array[value_stack.top-3]._endpointclass));						
			yyval._object = new QS._qss_p_.Structure_.Object_Custom_(
				_metadata._Name, _metadata, _parameters, new QS._qss_p_.Structure_.Declaration_Reference_(_objectclass, _class_declarations), _object_endpoints);
		}
        break;
      case 34: // @6 -> /* empty */
#line 850 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
		}
        break;
      case 35: // ObjectClass_Declaration -> KWOBJECT KWCLASS Metadata @6 Parameters_Declarations_Classes_Optional '{' '}' 
#line 854 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.ObjectClass_Custom_ _objectclass = new QS._qss_p_.Structure_.ObjectClass_Custom_(value_stack.array[value_stack.top-5]._metadata._Name, value_stack.array[value_stack.top-5]._metadata, value_stack.array[value_stack.top-3]._parameters, null);
			yyval._objectclass = _objectclass;
			this._environment = this._environment._Environment;					
			this._environment._Add	(_objectclass);
		}
        break;
      case 36: // @7 -> /* empty */
#line 866 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
			this._metadata_stack.Push(value_stack.array[value_stack.top-1]._metadata);			
		}
        break;
      case 37: // @8 -> /* empty */
#line 871 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._parameters_stack.Push(value_stack.array[value_stack.top-1]._parameters);				
		}
        break;
      case 38: // Operator_Declaration -> KWOPERATOR Metadata @7 Parameters_Declarations_Optional @8 Operator_Declaration_Body 
#line 875 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IOperator_ _operator = value_stack.array[value_stack.top-1]._operator;
			yyval._operator = _operator;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_operator);		
		}
        break;
      case 39: // Operator_Declaration_Body -> '(' Values_Incoming ')' Values_Outgoing '{' Values_Internal '}' 
#line 887 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IMetadata_ _metadata = this._metadata_stack.Pop();
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = this._parameters_stack.Pop(); 
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _class_parameters;
			IEnumerable<QS._qss_p_.Structure_.IDeclaration_> _class_declarations;
			_GenerateClassParametersAndDeclarations(_parameters, out _class_parameters, out _class_declarations);
			string _identifier = _metadata._Name;
			QS._qss_p_.Structure_.IOperatorClass_ _operatorclass = 
				new QS._qss_p_.Structure_.OperatorClass_Custom_(
					_identifier, new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", _identifier, string.Empty), _class_parameters, value_stack.array[value_stack.top-6]._values, value_stack.array[value_stack.top-4]._values);
			this._automatic_declarations.Add(_operatorclass);			
			yyval._operator = new QS._qss_p_.Structure_.Operator_Custom_(
				_metadata._Name, _metadata, _parameters, new QS._qss_p_.Structure_.Declaration_Reference_(_operatorclass, _class_declarations), value_stack.array[value_stack.top-6]._values, value_stack.array[value_stack.top-4]._values, value_stack.array[value_stack.top-2]._values);
		}
        break;
      case 40: // @9 -> /* empty */
#line 907 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
			this._metadata_stack.Push(value_stack.array[value_stack.top-1]._metadata);			
		}
        break;
      case 41: // @10 -> /* empty */
#line 912 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._parameters_stack.Push(value_stack.array[value_stack.top-1]._parameters);		
		}
        break;
      case 42: // OperatorClass_Declaration -> KWOPERATOR KWCLASS Metadata @9 Parameters_Declarations_Classes_Optional @10 OperatorClass_Declaration_Body 
#line 916 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IOperatorClass_ _operatorclass = value_stack.array[value_stack.top-1]._operatorclass;
			yyval._operatorclass = _operatorclass;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_operatorclass);
		}
        break;
      case 43: // OperatorClass_Declaration_Body -> '(' Values_Incoming ')' Values_Outgoing ';' 
#line 928 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IMetadata_ _metadata = this._metadata_stack.Pop();
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = this._parameters_stack.Pop(); 
			yyval._operatorclass = new QS._qss_p_.Structure_.OperatorClass_Custom_(_metadata._Name, _metadata, _parameters, value_stack.array[value_stack.top-4]._values, value_stack.array[value_stack.top-2]._values);
		}
        break;
      case 44: // Parameter_Declaration -> Parameter_Declaration_Value 
#line 963 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = value_stack.array[value_stack.top-1]._parameter;
		}
        break;
      case 45: // Parameter_Declaration -> Parameter_Declaration_Class 
#line 967 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = value_stack.array[value_stack.top-1]._parameter;
		}
        break;
      case 46: // Parameter_Declaration_Class -> KWVALUE KWCLASS IDENTIFIER 
#line 976 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._ValueClass, null);			
		}
        break;
      case 47: // Parameter_Declaration_Class -> KWVALUE '~' IDENTIFIER 
#line 980 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._ValueClass, null);			
		}
        break;
      case 48: // Parameter_Declaration_Class -> ValueClass_Unambiguous '~' IDENTIFIER 
#line 984 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._ValueClass, value_stack.array[value_stack.top-3]._valueclass);			
		}
        break;
      case 49: // Parameter_Declaration_Class -> Declaration_Reference '~' IDENTIFIER 
#line 988 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.Declaration_Parameter_ _parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, value_stack.array[value_stack.top-3]._declaration);
			yyval._parameter = _parameter;
			this._unresolved.Add(_parameter);			
		}
        break;
      case 50: // Parameter_Declaration_Value -> ValueClass_Unambiguous IDENTIFIER 
#line 1001 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._Value, value_stack.array[value_stack.top-2]._valueclass);			
		}
        break;
      case 51: // Parameter_Declaration_Value -> Declaration_Reference IDENTIFIER 
#line 1005 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameter = new QS._qss_p_.Structure_.Declaration_Parameter_(value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._Value, value_stack.array[value_stack.top-2]._declaration);
		}
        break;
      case 52: // Parameters_Declarations -> Parameter_Declaration ',' Parameters_Declarations 
#line 1016 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = new List<QS._qss_p_.Structure_.IParameter_>();
			yyval._parameters.Add(value_stack.array[value_stack.top-3]._parameter);
			yyval._parameters.AddRange(value_stack.array[value_stack.top-1]._parameters);	
			this._environment._Add	(value_stack.array[value_stack.top-3]._parameter);
		}
        break;
      case 53: // Parameters_Declarations -> Parameter_Declaration 
#line 1023 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = new List<QS._qss_p_.Structure_.IParameter_>();
			yyval._parameters.Add(value_stack.array[value_stack.top-1]._parameter);
			this._environment._Add	(value_stack.array[value_stack.top-1]._parameter);
		}
        break;
      case 54: // Parameters_Declarations_Optional -> LT Parameters_Declarations GT 
#line 1034 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = value_stack.array[value_stack.top-2]._parameters;
		}
        break;
      case 55: // Parameters_Declarations_Optional -> /* empty */
#line 1038 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = null;
		}
        break;
      case 56: // Parameters_Declarations_Classes -> Parameter_Declaration_Class ',' Parameters_Declarations_Classes 
#line 1047 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = new List<QS._qss_p_.Structure_.IParameter_>();
			yyval._parameters.Add(value_stack.array[value_stack.top-3]._parameter);
			yyval._parameters.AddRange(value_stack.array[value_stack.top-1]._parameters);	
			this._environment._Add	(value_stack.array[value_stack.top-3]._parameter);
		}
        break;
      case 57: // Parameters_Declarations_Classes -> Parameter_Declaration_Class 
#line 1054 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = new List<QS._qss_p_.Structure_.IParameter_>();
			yyval._parameters.Add(value_stack.array[value_stack.top-1]._parameter);
			this._environment._Add	(value_stack.array[value_stack.top-1]._parameter);
		}
        break;
      case 58: // Parameters_Declarations_Classes_Optional -> LT Parameters_Declarations_Classes GT 
#line 1065 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = value_stack.array[value_stack.top-2]._parameters;
		}
        break;
      case 59: // Parameters_Declarations_Classes_Optional -> /* empty */
#line 1069 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._parameters = null;
		}
        break;
      case 60: // Parameter_Value -> ValueClass_Unambiguous 
#line 1078 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._valueclass;
		}
        break;
      case 61: // Parameter_Value -> Declaration_Reference 
#line 1082 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declaration = value_stack.array[value_stack.top-1]._declaration;
		}
        break;
      case 62: // Parameters_Values -> Parameter_Value ',' Parameters_Values 
#line 1093 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
			yyval._declarations.Add(value_stack.array[value_stack.top-3]._declaration);
			yyval._declarations.AddRange(value_stack.array[value_stack.top-1]._declarations);		
		}
        break;
      case 63: // Parameters_Values -> Parameter_Value 
#line 1099 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
			yyval._declarations.Add(value_stack.array[value_stack.top-1]._declaration);
		}
        break;
      case 64: // Parameters_Values_Optional -> LT Parameters_Values GT 
#line 1109 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = value_stack.array[value_stack.top-2]._declarations;
		}
        break;
      case 65: // Parameters_Values_Optional -> /* empty */
#line 1113 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._declarations = null;
		}
        break;
      case 66: // @11 -> /* empty */
#line 1218 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
			this._metadata_stack.Push(value_stack.array[value_stack.top-1]._metadata);
		}
        break;
      case 67: // @12 -> /* empty */
#line 1223 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._parameters_stack.Push(value_stack.array[value_stack.top-1]._parameters);
		}
        break;
      case 68: // Value_Declaration -> KWVALUE Metadata @11 Parameters_Declarations_Optional @12 Value_Declaration_Body 
#line 1227 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IValue_ _value = value_stack.array[value_stack.top-1]._value;
			yyval._value = _value;
			this._environment = this._environment._Environment;			
			this._environment._Add	(_value);
		}
        break;
      case 69: // Value_Declaration_Body -> '{' Values_Members '}' 
#line 1239 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IMetadata_ _metadata = this._metadata_stack.Pop();
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = this._parameters_stack.Pop(); 
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _class_parameters;
			IEnumerable<QS._qss_p_.Structure_.IDeclaration_> _class_declarations;
			_GenerateClassParametersAndDeclarations(_parameters, out _class_parameters, out _class_declarations);
			string _identifier = _metadata._Name;
			QS._qss_p_.Structure_.IValueClass_ _valueclass = 
				new QS._qss_p_.Structure_.ValueClass_Custom_(
					_identifier, new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", _identifier, string.Empty), _class_parameters, value_stack.array[value_stack.top-2]._values);
			this._automatic_declarations.Add(_valueclass);			
			yyval._value = new QS._qss_p_.Structure_.Value_Custom_(
				_metadata._Name, _metadata, _parameters, new QS._qss_p_.Structure_.Declaration_Reference_(_valueclass, _class_declarations), value_stack.array[value_stack.top-2]._values);
		}
        break;
      case 70: // Value_Incoming -> ValueClass Metadata_Internal 
#line 1259 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._value = new QS._qss_p_.Structure_.Value_Incoming_(value_stack.array[value_stack.top-1]._metadata._Name, value_stack.array[value_stack.top-1]._metadata, value_stack.array[value_stack.top-2]._valueclass);
		}
        break;
      case 71: // Value_Member -> ValueClass Metadata_Internal 
#line 1268 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._value = new QS._qss_p_.Structure_.Value_Member_(value_stack.array[value_stack.top-1]._metadata._Name, value_stack.array[value_stack.top-1]._metadata, value_stack.array[value_stack.top-2]._valueclass);
		}
        break;
      case 72: // Value_Internal -> ValueClass Metadata_Internal 
#line 1277 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._value = new QS._qss_p_.Structure_.Value_Internal_(value_stack.array[value_stack.top-1]._metadata._Name, value_stack.array[value_stack.top-1]._metadata, value_stack.array[value_stack.top-2]._valueclass);
		}
        break;
      case 73: // Value_Outgoing -> ValueClass Metadata_Internal 
#line 1286 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._value = new QS._qss_p_.Structure_.Value_Outgoing_(value_stack.array[value_stack.top-1]._metadata._Name, value_stack.array[value_stack.top-1]._metadata, value_stack.array[value_stack.top-2]._valueclass);
		}
        break;
      case 74: // Value_Reference -> IDENTIFIER 
#line 1295 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.Declaration_Reference_ _reference = 
				new QS._qss_p_.Structure_.Declaration_Reference_(this._environment, value_stack.array[value_stack.top-1]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._Value, null);
			this._unresolved.Add(_reference);
			yyval._value = _reference; 
		}
        break;
      case 75: // Values_Incoming -> Values_Incoming_Body 
#line 1307 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = value_stack.array[value_stack.top-1]._values;
		}
        break;
      case 76: // Values_Incoming -> /* empty */
#line 1311 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = null;
		}
        break;
      case 77: // Values_Incoming_Body -> Value_Incoming ',' Values_Incoming_Body 
#line 1320 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
			this._environment._Add(value_stack.array[value_stack.top-3]._value);		
		}
        break;
      case 78: // Values_Incoming_Body -> Value_Incoming 
#line 1327 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-1]._value);
			this._environment._Add(value_stack.array[value_stack.top-1]._value);		
		}
        break;
      case 79: // Values_Internal -> Values_Internal_Body 
#line 1338 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = value_stack.array[value_stack.top-1]._values;
		}
        break;
      case 80: // Values_Internal -> /* empty */
#line 1342 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = null;
		}
        break;
      case 81: // Values_Internal_Body -> Value_Internal ';' Values_Internal_Body 
#line 1351 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
			this._environment._Add(value_stack.array[value_stack.top-3]._value);		
		}
        break;
      case 82: // Values_Internal_Body -> Value_Internal ';' 
#line 1358 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-2]._value);
			this._environment._Add(value_stack.array[value_stack.top-2]._value);		
		}
        break;
      case 83: // Values_Outgoing -> ':' Values_Outgoing_Body 
#line 1369 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = value_stack.array[value_stack.top-1]._values;
		}
        break;
      case 84: // Values_Outgoing -> /* empty */
#line 1373 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = null;
		}
        break;
      case 85: // Values_Outgoing_Body -> Value_Outgoing ',' Values_Outgoing_Body 
#line 1382 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
			this._environment._Add(value_stack.array[value_stack.top-3]._value);		
		}
        break;
      case 86: // Values_Outgoing_Body -> Value_Outgoing 
#line 1389 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-1]._value);
			this._environment._Add(value_stack.array[value_stack.top-1]._value);		
		}
        break;
      case 87: // Values_Members -> Value_Member ';' Values_Members 
#line 1400 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
			this._environment._Add(value_stack.array[value_stack.top-3]._value);		
		}
        break;
      case 88: // Values_Members -> /* empty */
#line 1407 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
		}
        break;
      case 89: // Values_Members_Commas -> Values_Members_Commas_Body 
#line 1416 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = value_stack.array[value_stack.top-1]._values;
		}
        break;
      case 90: // Values_Members_Commas -> /* empty */
#line 1420 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = null;
		}
        break;
      case 91: // Values_Members_Commas_Body -> Value_Member ',' Values_Members_Commas_Body 
#line 1429 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
			this._environment._Add(value_stack.array[value_stack.top-3]._value);		
		}
        break;
      case 92: // Values_Members_Commas_Body -> Value_Member 
#line 1436 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-1]._value);
			this._environment._Add(value_stack.array[value_stack.top-1]._value);		
		}
        break;
      case 93: // Values_References -> Value_Reference ',' Values_References 
#line 1447 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-3]._value);
			yyval._values.AddRange(value_stack.array[value_stack.top-1]._values);		
		}
        break;
      case 94: // Values_References -> Value_Reference 
#line 1453 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._values = new List<QS._qss_p_.Structure_.IValue_>();
			yyval._values.Add(value_stack.array[value_stack.top-1]._value);
		}
        break;
      case 95: // ValueClass -> ValueClass_Unambiguous 
#line 1463 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = value_stack.array[value_stack.top-1]._valueclass;
		}
        break;
      case 96: // ValueClass -> ValueClass_Reference 
#line 1467 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = value_stack.array[value_stack.top-1]._valueclass;
		}
        break;
      case 97: // ValueClasses -> ValueClass ',' ValueClasses 
#line 1476 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclasses = new List<QS._qss_p_.Structure_.IValueClass_>();
			yyval._valueclasses.Add(value_stack.array[value_stack.top-3]._valueclass);
			yyval._valueclasses.AddRange(value_stack.array[value_stack.top-1]._valueclasses);
		}
        break;
      case 98: // ValueClasses -> ValueClass 
#line 1482 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclasses = new List<QS._qss_p_.Structure_.IValueClass_>();
			yyval._valueclasses.Add(value_stack.array[value_stack.top-1]._valueclass);
		}
        break;
      case 99: // @13 -> /* empty */
#line 1492 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._environment = new QS._qss_p_.Structure_.Environment_(this._environment);
			this._metadata_stack.Push(value_stack.array[value_stack.top-1]._metadata);			
		}
        break;
      case 100: // @14 -> /* empty */
#line 1497 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			this._parameters_stack.Push(value_stack.array[value_stack.top-1]._parameters);
		}
        break;
      case 101: // ValueClass_Declaration -> KWVALUE KWCLASS Metadata @13 Parameters_Declarations_Classes_Optional @14 ValueClass_Declaration_Body 
#line 1501 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IValueClass_ _valueclass = value_stack.array[value_stack.top-1]._valueclass;
			yyval._valueclass = _valueclass;			
			this._environment = this._environment._Environment;					
			this._environment._Add	(_valueclass);
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = ((QS._qss_p_.Structure_.IDeclaration_) _valueclass)._Parameters;
			List<QS._qss_p_.Structure_.IDeclaration_> _declarations = null;
			if (_parameters != null)
			{
				_declarations = new List<QS._qss_p_.Structure_.IDeclaration_>();
				foreach (QS._qss_p_.Structure_.IParameter_ _parameter in _parameters)
					_declarations.Add(new QS._qss_p_.Structure_.Declaration_Reference_(_parameter, null));
			}
			string _identifier =  ((QS._qss_p_.Structure_.IDeclaration_) _valueclass)._Metadata._Name;
			QS._qss_p_.Structure_.IValue_ _value = 
				new QS._qss_p_.Structure_.Value_Custom_(
					_identifier, new QS._qss_p_.Structure_.Metadata_(QS.Fx.Base.ID.NewID().ToString(), "0", _identifier, string.Empty), _parameters, 
						new QS._qss_p_.Structure_.Declaration_Reference_(_valueclass, _declarations), 
						((QS._qss_p_.Structure_.IValueClass_Custom_) _valueclass)._Values);
			this._automatic_declarations.Add(_value);			
		}
        break;
      case 102: // ValueClass_Declaration_Body -> '{' Values_Members '}' 
#line 1528 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.IMetadata_ _metadata = this._metadata_stack.Pop();
			IEnumerable<QS._qss_p_.Structure_.IParameter_> _parameters = this._parameters_stack.Pop(); 
			yyval._valueclass = new QS._qss_p_.Structure_.ValueClass_Custom_(_metadata._Name, _metadata, _parameters, value_stack.array[value_stack.top-2]._values);
		}
        break;
      case 103: // ValueClass_Reference -> IDENTIFIER Parameters_Values_Optional 
#line 1547 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			QS._qss_p_.Structure_.Declaration_Reference_ _reference = 
				new QS._qss_p_.Structure_.Declaration_Reference_(this._environment, value_stack.array[value_stack.top-2]._identifier, QS._qss_p_.Structure_.Declaration_.Type_._ValueClass, value_stack.array[value_stack.top-1]._declarations);
			this._unresolved.Add(_reference);
			yyval._valueclass = _reference; 
		}
        break;
      case 104: // ValueClass_Unambiguous -> KWBOOL 
#line 1559 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = QS._qss_p_.Structure_.ValueClass_Primitive_._Boolean;
		}
        break;
      case 105: // ValueClass_Unambiguous -> KWINT 
#line 1563 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = QS._qss_p_.Structure_.ValueClass_Primitive_._Integer;
		}
        break;
      case 106: // ValueClass_Unambiguous -> '(' ValueClasses ')' 
#line 1567 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = new QS._qss_p_.Structure_.ValueClass_Tuple_(value_stack.array[value_stack.top-2]._valueclasses);
		}
        break;
      case 107: // ValueClass_Unambiguous -> '{' ValueClass '}' 
#line 1571 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"
			{
			yyval._valueclass = new QS._qss_p_.Structure_.ValueClass_Set_(value_stack.array[value_stack.top-2]._valueclass);
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (((Tokens)terminal).ToString() != terminal.ToString())
      return ((Tokens)terminal).ToString();
    else
      return CharToString((char)terminal);
  }

#line 1576 "G:\IsisGridCloud\isisgridcloud\Liveobjects-Source\liveobjects_7\_qss_p_\Parser_\Parser_.y"




}
}
